add validation that generate-mjml-react.ts has been run

diff --git a/.github/workflows/CI_PR_merge_checks.yml b/.github/workflows/CI_PR_merge_checks.yml
--- a/.github/workflows/CI_PR_merge_checks.yml
+++ b/.github/workflows/CI_PR_merge_checks.yml
@@ -25,3 +25,22 @@ jobs:
         run: yarn lint
       - name: Test
         run: yarn test
+      - name: Validate generate-mjml-react.ts has been run
+        run: |
+          node --require ts-node/register scripts/generate-mjml-react.ts
+          result=$(git diff --quiet --exit-code HEAD || echo "fail")
+          if [ "$result" == "fail" ]; then
+            echo ">>> MJML REACT CHECK FAILED! <<<"
+            echo "Common cause: upgraded mjml or edited an mj-custom-component -> run"
+            echo ""
+            echo "    $ yarn generate-mjml-react"
+            echo ""
+            git --no-pager diff --stat HEAD
+            echo ""
+            echo "=============="
+            echo ""
+            git --no-pager diff HEAD
+            echo ""
+            echo "=============="
+            exit 1
+          fi
